### PR TITLE
Fix outlierDetection.R

### PR DESCRIPTION
**Pull request by nturaga**
- We need to make sure we "importFrom" the required packages and functions when writing new functions.

- We also need to adhere to the same coding practices that are available across the pacakge.

- After every merge, make sure R CMD build and check produce no WARNINGS and minimal NOTES.

### CODE REVIEW

**Comment by andrewGhazi** [comment]
- The functions added to NAMESPACE here are all called explicitly with a double colon :: and their respective packages are in `Imports:` so I don't think they need to be `importFrom()`ed. I called `devtools::document()` before committing and I think it would have caught that if it was necessary.
- For style I generally run it through `styler::style_file(style = biocthis::bioc_style)` as the last step before committing. I generally dislike the aesthetics of what that produces but Ludwig+Smriti+I+others settled on that approach as the easiest way for us to stay consistent as a group. 
- I'm agnostic on other things like double pound symbol before comments, but I can stick with whatever seems best. Personally I think ctrl+shift+/ in RStudio is the best way to reflow long comments.
- What's the purpose of splitting the arguments to `stop()`? Looking at `?stop()` it seems like the first thing it does is paste them back together.
- I don't see any new warnings or notes that are averted here? But yes I'll make sure to keep an eye on the check results with future commits.

**Comment by lgeistlinger** [comment]
> The functions added to NAMESPACE here are all called explicitly with a double colon :: and their respective packages are in Imports: so I don't think they need to be importFrom()ed.

In my packages, also use the `package::function` notation and add to `Imports:` of the `DESCRIPTION` file, instead of declaring imports explicit via `importFrom` and adding to `NAMESPACE`. If you are on board with that @nturaga, I would prefer to go ahead with this route for importing dependencies.

> For style I generally run it through styler::style_file(style = biocthis::bioc_style)

That's fine, but there are still a couple of style inconsistencies that need to be cleaned up at some point. For example, we would like `calculateOutlierScore` to use consistent notation for their arguments, either Bioc style (separate by a dot as eg for argument `group.var`) or tidyverse style (separte by an underscore as eg for arguments `use_pcs` and `prediction_thresh`). I am ok with both as long as we agree on one notation, I am obviously in favor of the Bioc notation though.

> What's the purpose of splitting the arguments to stop()? Looking at ?stop() it seems like the first thing it does is paste them back together.

Simply to break long statements at the 80 char limit,

**Comment by nturaga** [comment]
`@importFrom` promotes better code organization and clarity. It allows you to explicitly import only the specific functions you need from another package. This keeps your code focused and avoids cluttering the namespace with unused objects.

Importing the entire namespace with @import can lead to name collisions. If you have functions with the same name in your package and the imported one, your code might break. @importFrom helps prevent this by only bringing in specific functions.

Importing only what you need can improve memory usage and potentially speed up your code execution. @import loads everything from the other package, even if you don't use it all. Some of the packages we import are quite large. 

At the end of the day, I'm in favor of whatever way you prefer.  My recommendation is use @importFrom.

**Comment by andrewGhazi** [comment]
> Importing the entire namespace with `@import` can lead to name collisions. If you have functions with the same name in your package and the imported one, your code might break. `@importFrom` helps prevent this by only bringing in specific functions.

This is true, but we aren't importing the entire namespace of the dependencies because we aren't using `@import`. You can verify that everything in the NAMESPACE file is `importFrom()`, even though we didn't specify the respective tag in the roxygen2 comments. This is because `devtools::document()` looks through the code and if there's a pkg::fun() call that is missing from NAMESPACE it will add it as an `importFrom()`.

**Comment by lgeistlinger** [comment]
> This is true, but we aren't importing the entire namespace of the dependencies because we aren't using @import

Agreed.

> This is because devtools::document() looks through the code and if there's a pkg::fun() call that is missing from NAMESPACE it will add it as an importFrom()

This is not exactly how it works @andrewGhazi (see eg. your `isotree::isolation.forest` call [here](https://github.com/ccb-hms/scDiagnostics/blob/feab3cf2c1c6555b938d3d4ea6ad29bcb0aba21d/R/outlierDetection.R#L108) and the absence of an `importFrom(sotree, isolation.forest)` directive in the NAMESPACE file [here](https://github.com/ccb-hms/scDiagnostics/blob/main/NAMESPACE)).

What happens when we use the `pkg::fun` notation and import `pkg` in the `DESCRIPTION` file is that the namespace of `pkg` is attached at runtime and `fun` is called from the namespace of `pkg`. This is different to using `importFrom(pkg, fun)` where the function is actually imported into our package's namespace.

There are two benefits of using 

1. Avoiding namespace conflicts:

Let’s say we have two packages `foo1` and `foo2` both defining a function `bar`. The name is the same but the function actually does very different things in each package. Now our function would want to make use of 

```
#’ @importFrom(foo1, bar)
#’ @importFrom(foo2, bar)
myFunction(x)
{
	# intending to call foo1::bar, but will actually call foo2::bar
	y <- bar(x)
	# intending to call foo2::bar
	z <- bar(z)
	return(y) 
} 
``` 	

The problem here is that the import of `bar` from `foo1` will be replaced by the import of `bar` from `foo2`.

This issue got some prominence when somebody tried to use the `select` function defined in both the `dplyr` package in the tidyverse and the `AnnotationDbi` package in Bioconductor, where both `select` functions do very different things. 

2. Readability / Comprehension:

When there are a lot of imported functions, it is sometimes difficult to understand and debug where the function is coming from. In this regard I like the `pkg::fun` notation because it makes very clear what is a function of my package and what is a function of another package and where do I need to look if things are breaking.

> I'm ok with closing the PR if you do not want to change what is there already.

I am ok with merging given that you’ve already put in the work, but I'd like to agree on an importing strategy for this package going forward.

Looking at your edits it seems you actually you do both, you do have the `importFrom` directives but you also use the `pkg:fun` notation. That would of course also work, because in this case we seem to have the two above mentioned benefits. The example would then look like this:

#’ @importFrom(foo1, bar)
#’ @importFrom(foo2, bar)
myFunction(x)
{
	# intending to call foo1::bar, but will actually call foo2::bar
	y <- foo1::bar(x)
	# intending to call foo2::bar
	z <- foo2::bar(z)
	return(y) 
}  	

It seems additional effort at first glance, but I can see that there is a benefit by not attaching the entire namespace of `foo1` and `foo2` which I think is going to happen implicitly when calling `foo1::bar` and not having `@importFrom(foo1, bar)` @nturaga?

**Comment by andrewGhazi** [comment]
Ah, thanks for the clarification Ludwig. You're right, I was getting confused between the edits in @ntu
's PR and the behavior of devtools::document().

`::` without @importFrom doesn't attach the package, but it does load it. So you don't get the name clashes but there probably is some load time if the dependencies are large. https://r-pkgs.org/dependencies-in-practice.html#sec-dependencies-in-imports-r-code

**Pull request closed without merging**
