### PR TITLE
Entropy

### PR DESCRIPTION
**Pull request by andrewGhazi**
Function to run outlier detection by an input cluster variable `clusterVar`. Currently this requires unique column names to ensure that the result is returned with the columns in the same order.

### CODE REVIEW

**Comment by lgeistlinger** [comment]
Thanks @andrewGhazi. A couple of points 

- I am confused that this pull request is named "Entropy" as this seems to rather be functionality for "Outlier detection"
- The latest commit doesn't pass R CMD check and [fails due to missing dependencies](https://github.com/ccb-hms/scDiagnostics/actions/runs/8706339157/job/23878679448?pr=27). As we are preparing for submission to Bioconductor, going forward I'd like pull requests to always pass R CMD check. 
- I was wondering whether it is necessary to have a separate function `calculateOutlierScoreByCluster`? My preference would be for the general `calculateOutlierScore` to have a `group.var` argument that is `NULL` by default and will then compute outlier scores across the dataset. Or if `group.var` is a categorical variable in the `colData`, where cluster membership is just one (particularly useful) example, the outlier scores would then be computed by group.
- I would like us to separate calculations and plotting in general and for the `calculateOutlierScore` function in particular. I think the plotting via `scater::PlotReducedDim` [here](https://github.com/ccb-hms/scDiagnostics/blob/9df5a06092028e0fd3bfb862ce71b9eec2de6dd5/R/outlierDetection.R#L166) can just go into the vignette, but if you feel strongly about having it as a function, then let's put it in a function `plotOutlierScore` that consumes the output of `calculateOutlierScore`.
- Please no piping (`|>`) in package code (my personal preference)

**Comment by andrewGhazi** [comment]
- Oops I think it's called entropy by default because I was committing from the same branch that I implemented the entropy functionality from. 
- Not sure why R CMD check is failing here, none of those dependencies are new and some aren't even used in this function...
- group.var argument makes sense, I'll switch it around.
- `plotOutlierScore` seems fine, I'll remove the plotting behavior and add it there.
- Okay, I'll remove the pipes.

**Comment by lgeistlinger** [comment]
> Not sure why R CMD check is failing here, none of those dependencies are new and some aren't even used in this function...

It seems your `entropy` branch doesn't have the [latest updates](https://github.com/ccb-hms/scDiagnostics/commit/898a9908562206487ee6381c8d85190ddd2aadc7) from Nitesh and me? That is because the `DESCRIPTION` file looks like the old one on the `entropy` which is causing these `NAMESPACE` vs `DESCRIPTION` file issues. I think you need to pull these changes first, before pushing new stuff on top of it.

**Comment by lgeistlinger** [comment]
I guess this can be closed @andrewGhazi?

**Pull request closed without merging**
